# used by SEO tag
title: jackw01
description: jackw01
url: https://jackw01.github.io
author:
  name: Jack Whittaker
  url: https://jackw01.github.io
logo: logo.png
social:
  name: Jack Whittaker
  links:
    - https://github.com/jackw01
    - https://www.linkedin.com/in/jack-whittaker-b35961183/
google_site_verification: WVEP9YX5HRoViEFRMzY6MPy4xwbEH2PgxnJHjcvbFcE
# end seo
name: jackw01.github.io
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
plugins:
  - jekyll-seo-tag
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
